### ISSUE TITLE
Merge data source: Shall be possible to give a custom name to a merged data source

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#123]
When having multiple merge data sources it would be nice to have a custom name for each source. Thus we'd like to have the re-namable.

**Comment by Kittyfisto** [comment]
Will do, I've even got the control to allow in-place editing of the name (via a hidden double click). Might make it into this nights build.

**Comment by Kittyfisto** [comment]
@BenKenobi85 Included in 0.7.0, let me know what you think of it
