### ISSUE TITLE
Tailviewer shall optionally report time delta between log entries

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#124]
For log files having a time (and/or date) stamp at the beginning of each log entry tailviewer is able to use this information for merging data sources.

Another use of a time stamp is to calculate the relative distance to another log entry. For our use cases it would be very beneficial to have tailviewer calculating the time delta between log entries - for logs having at least two entries - and display these in an extra column besides the line numbers.
The user shall be able to turn this feature on or off.

Example: 

![image](https://user-images.githubusercontent.com/26541111/33022746-7798d1ba-ce06-11e7-9124-1b8f1844ca29.png)

**Comment by Kittyfisto** [comment]
Sensible enhancement. It'll require some iterations but I'll have a beta build for this feature available in December, I think.

**Comment by Kittyfisto** [comment]
Screenshot from the current WIP: 
![image](https://user-images.githubusercontent.com/11990827/33849427-d04d38cc-deb0-11e7-9485-a40ef0833418.png)

I'm currently toying around with how to deal with the different orders of magnitude: You can have lines be 1ms apart and then the next 5 seconds or even 5 hours. On the one hand, I really hate to figure out how much 1234566ms actually is, but the approach above seems to be too uneven and looks ugly.

@BenKenobi85 Got any feedback to help me out? :)

**Comment by Kittyfisto** [comment]
First iteration has been shipped, any feedback can be collected in new issues.
