### ISSUE TITLE
Shall have an option to configure scroll speed

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#126]
Viewing large logs is ultra slow as vertical scrolling using the mouse wheel only increments by 1 line.

Having an option to adjust this speed to a variable number of lines would make life easier.
E.g. 3 lines per wheel tick is a commonly used setting.

**Comment by Kittyfisto** [comment]
I'll change the default from 1 to 3 while we're at it. Won't take long.
