### ISSUE TITLE
Titlebar shall contain more information

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#127]
When a file is selected and it's part of a merged data source, then the path in the title bar should contain something like: "Merged Data Source -> F:\foo\log.txt [A]" where A is the character of the file (probably displayed in same color).

**Comment by Kittyfisto** [comment]
Will be done. I think I'll make those parent titles hyperlinks as there can be a variable amount of parents with #125 and this way you can at least jump to a parent without opening the data sources panel.

**Comment by Kittyfisto** [comment]
Available with [v0.8.1](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.1)
