### ISSUE TITLE
Move ugly progress bar to the bottom

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#129]
The progress bar doesn't fit to the top of the screen, it should be moved to the bottom as shown here:

![image](https://user-images.githubusercontent.com/11990827/33314906-5a533ef4-d42f-11e7-9ef5-37fc6eaa5530.png)

The bottom bar shows all kinds of information of the current log file and should also show Tailviewer's progress of reading/filtering it.

**Comment by BenKenobi85** [comment]
Instead of having a progress bar it would be sufficient to have a numerical marker in the lower right corner, e.g. (80%). The marker shall only be visible when there's an ongoing update to the view -> no display for fully processed files.

**Comment by Kittyfisto** [comment]
@BenKenobi85  I'm not so sure about not having any progress bar. This progress bar exists because it was never apparent if the file is now fully filtered or not (which is really important when filtering takes 10 seconds for Gigabytes or files). I'm not sure if N% is visible enough to show the user that processing is finished, which may lead the user to wrong conclusions.
