### ISSUE TITLE
Action center reports 99 errors

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#134]
![image](https://user-images.githubusercontent.com/26541111/33327949-00652e46-d459-11e7-8d82-6511fa2b991a.png)

[Tailviewer.log](https://github.com/Kittyfisto/Tailviewer/files/1510475/Tailviewer.log)

**Comment by Kittyfisto** [comment]
Was caused by binding which defaulted to TwoWay whereas OneWay was desired.
