### ISSUE TITLE
Go to data source doesn't work on merged data sources

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#152]
### Current behaviour

Merged data sources don't appear in the list of data sources when pressing Ctrl+T.

### Expected behaviour

Merged data sources should appear in the list of data sources when pressing Ctrl+T.

### Steps to reproduce the problem

1. Start Tailviewer
2. Select a log file
3. Have at least one merged data source (maybe give it a custom name)
4. Press Ctrl+T
5. Enter the name of the merged data source

**Comment by Kittyfisto** [comment]
@oleg-abr wanna take a look at this one afterwards?

**Comment by oleg-abr** [comment]
Sure thing.
Ctrl+T is like "Go To Everything" in R#?

**Comment by Kittyfisto** [comment]
Yup
