### ISSUE TITLE
 Merged data source displays wrong origin.

### ISSUE THREAD

**Issue by oleg-abr** [Kittyfisto/Tailviewer#154]
### Current behaviour

Wrong origin is displayed in the second column of the megred data source row. See yellow marked areas.

![wrongdatasource](https://user-images.githubusercontent.com/10827743/34210002-a071ed60-e594-11e7-8159-f3cf7d26d601.PNG)

### Expected behaviour

In the first marked area Nestor.log is expected.
In the second marked area Tsma.log is expected.

### Steps to reproduce the problem

Not sure. Maybe need a log with a long stack trace?

**Comment by Kittyfisto** [comment]
I'd guess that this is caused due to having a multiline entry.
Can you do me a favour and confirm if this problem vanishes when you enable singleline (View => Single line)

Either way I'll have this fixed in the next patch.

**Comment by oleg-abr** [comment]
yepp, it vanishes all right.

**Comment by Kittyfisto** [comment]
Fixed with [v0.8.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)

**Comment by Kittyfisto** [comment]
This issue re-appeared in v0.9.

**Comment by Kittyfisto** [comment]
@oleg-abr Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
