### ISSUE TITLE
Wrong Counter on Merged Data Source

### ISSUE THREAD

**Issue by oleg-abr** [Kittyfisto/Tailviewer#155]
### Current behaviour

Look at the Top Counter for number of errors and warnings. It cheerfully deceiving you, saying "there are no errors or warnings, sir, oh no, don't you worry".

![noerrorsmerged](https://user-images.githubusercontent.com/10827743/34222404-be076efa-e5bb-11e7-9773-5d43f663ac3b.PNG)

### Expected behaviour

I expecting nothing but truth.

**Comment by Kittyfisto** [comment]
Fixed with the same rewrite which fixed #154

**Comment by Kittyfisto** [comment]
Fixed with [v0.8.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)
