### ISSUE TITLE
Allow to change data source via shortcut

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#163]
Currently changing the active data source requires to use the data source tree view. For users focusing on the log data want to maximize the visible area used for data it's most common to collapse the data source tree view. While in collapsed mode, changing the active source includes to un-collapse the data source view, select the new data source and collapse it again.

Thus switching between data sources very often is a tedious task. It would be very beneficial to have a keyboard shortcut for this.

Example of a good solution might be the notepad++ implementation which uses [strg] + [tab] for bringing a switchable list of available data source items. While holding [strg] down each keypress of [tab] toggles to next item in the data source list.

**Comment by Kittyfisto** [comment]
There exists are feature 'go to file' (strg+T) which brings up a dialog where the name of the file to be opened can be entered. The dialog also features a list of suggestions of files which match the entered searchterm.

However I can implement more shortcuts such as switching to the next / previous file in the list.

**Comment by Kittyfisto** [comment]
Fixed with [v0.8.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)
