### ISSUE TITLE
Activating an existing quick filter doesn't always have an effect

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#166]
Happens in latest alpha builds only: Sometimes I can activate a quick filter, but it doesn't have any effect on the log file, even when there are no matches.

Was probably broken during refactoring (why didn't any test catch this?!?).

**Comment by PhilLab** [comment]
Can reproduce this in the latest release 0.8.1

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
