### ISSUE TITLE
Always provide an "empty" quick filter when opening the quick filter pane

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#175]
To create quick filters the user currently has to either (A) open the quick filter pane and press the "+" button or (B) to use the short cut. As stupid me struggles to remember shortcuts I'll always stick with path (A) which takes 2 clicks, see:

![image](https://user-images.githubusercontent.com/26541111/50764015-c3608d80-1271-11e9-8720-716e0666961d.png)

Stupid me also is lazy. Having an "empty" quick filter being created every time the user opens the quick filter bar (condition: there's no empty one there yet) would reduce the necessary user interactions to just one click, e.g. one less than using path (A).

**Comment by Kittyfisto** [comment]
The feature will be part of the next release. It can already be accessed via [the latet build](https://ci.appveyor.com/project/Kittyfisto/sharptail/builds/23292262), if need be

**Comment by Kittyfisto** [comment]
Fixed with [v0.8.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)
