### ISSUE TITLE
Multi Line log

### ISSUE THREAD

**Issue by abani1986** [Kittyfisto/Tailviewer#185]
Tail viewer not detecting multi line log files.

**Comment by Kittyfisto** [comment]
Sorry for taking so long, I've been busier than expected in the last few weeks. I haven't forgotten about this and I've started working on a fix yesterday evening. You can expect a fix and a new release on the beginning of next week ;)


This is a duplicate of https://github.com/Kittyfisto/Tailviewer/issues/183.

**Comment by Kittyfisto** [comment]
@abani1986 Please let me know if this is fixed for you with [v0.8](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)
