### ISSUE TITLE
GUI - Provide a "minimized" mode

### ISSUE THREAD

**Issue by Swiftpaws** [Kittyfisto/Tailviewer#201]
### Current behaviour

The left sidebar is not always used and takes up valuable space

### Expected behaviour

Provide a way to fully collapse the left hand sidebar - A ToggleButton in the titlebar could be sufficient

**Comment by Kittyfisto** [comment]
Good idea, will be done with the next (0.9) update.

**Comment by Kittyfisto** [comment]
Done. There now exists a little chevron in the lower left (right beneath the about icon) which expands / collapses the side panel. It's part of the latest CI build and will be part of the next release. Let me know if this helps / if you have any more suggestions!

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
