### ISSUE TITLE
Find All Window

### ISSUE THREAD

**Issue by Swiftpaws** [Kittyfisto/Tailviewer#210]
The following functionality could be very useful:

Add a button on the right side of the search box -> "Find all in current file"
This opens a new window on the bottom side which contains all log lines that match the given search string.
If you select one of the lines the "main" editor should scroll to the line number.

Examples of this:
Baretail -> http://www.baremetalsoft.com/baretailpro/screenshot_main.gif
And of course notepad++

**Comment by Kittyfisto** [comment]
I really like the idea. Currently one can do a search, but it's a bit tedious to jump from hit to hit until you find the one you're looking. One can also enable a filter find the line and disable a filter, but there's still an outstanding bug where tailviewer won't remember the line you have previously selected so you would have to select it again and it takes a few more clicks. In the mean time, you could use the shortcut to create a new filter strg+shift+n to do the filtering really quick, but there's none to disable the filter.

Concerning the actual implementation, I'm torn on whether to re-use the layout from Notepad++ or to try to find a way to achieve this with the right-side panel. The obvious down-side of the panel would be the lack of horizontal space. I'll probably have to play around a bit to find the best place for it.

Anyways, I'll try to have it implemented in the next (0.9) release.

**Comment by Kittyfisto** [comment]
So I've had some time to start this feature. Upon trying, I've ditched my original idea and simply copied the notepad++ approach.

Currently there's no highlighting of the searched result in the small view on the bottom and the height is fixed (relative to the window height) and cannot be changed by a user.

The current result looks like this:
![image](https://user-images.githubusercontent.com/11990827/62233954-ec8d6a80-b3c9-11e9-99f0-467ca3d1a376.png)

Feel free to try it out ([v0.9.0.813](https://ci.appveyor.com/project/Kittyfisto/sharptail/build/artifacts)) and give me feedback, if you've got time. I'm not really happy about the visuals just yet, but I also don't have an idea on how to improve it.

**Comment by Swiftpaws** [comment]
Looks good already. The only thing I would currently change is to leave the status bar at the bottom.

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
