### ISSUE TITLE
Tailviewer don't start

### ISSUE THREAD

**Issue by eNovware** [Kittyfisto/Tailviewer#214]
### Current behaviour

Since 2 days, Tailviewer.exe don't start anymore.
When I double click nothing happens, no error message.

I'm on Windows 10 64b Familly Version 1903 (18362.356)

### Expected behaviour

Shoudl start like previously.

### Steps to reproduce the problem

I really don't know.

**Comment by Kittyfisto** [comment]
That's strange. What Tailviewer version do you have installed / Did you install the latest version?

Can you please forward me the log files from "%LocalAppData%\Tailviewer\"? On top of that, could you please take a look at the Event Viewer and see if an error about a crashing application is logged at the appropriate time?
1. Press Windows Key
2. Type eventvwr
3. Wait for window to open, select Windows logs
4. Select Application
5. Click Filter Current Log in the right-hand side
6. Select Critical and Error, Press Ok
7. See if there's an error right around the time you tried to start tailviewer.

The event's general description should mention Tailviewer.exe (if there is such an event), please send me the entire "general" page of the event (or you could right click on the event and export it via "Save Selected Events..."). Either way I'll take a look right away.

For the record, I'm running on Windows 10 Enterprise Build 1809 and Tailviewer (0.9.0.814) is running there, not that that's any consolation to you.

When I get home I'll have access to Windows 10 Personal Edition and I'll take a look if it's working there too.

**Comment by eNovware** [comment]
Hi, thanks for your fast answer !

> What Tailviewer version do you have installed / Did you install the latest version?
-> I have 0.8.1.701 version (from Tailviewer.exe), so looks like the latest one.

Here is the last Tailviewer.log content (looks like usefull !!!)
`2019-09-26 13:46:46,269 [1] INFO  Tailviewer.App - Starting tailviewer...
2019-09-26 13:46:46,276 [1] INFO  Tailviewer.App - Commandline arguments: 
2019-09-26 13:46:46,278 [1] INFO  Tailviewer.App - Environment: 
Tailviewer: v0.8.1.701, 32bit
.NET Environment: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.18362.0, 64bit
Current directory: C:\Windows\system32
2019-09-26 13:46:46,461 [1] INFO  Tailviewer.Archiver.Plugins.PluginGroup - Loaded plugin 'C:\Program Files\Tailviewer\Plugins\Tailviewer.Analysis.Count.0.7.tvp'
2019-09-26 13:46:46,479 [1] INFO  Tailviewer.Archiver.Plugins.PluginGroup - Loaded plugin 'C:\Program Files\Tailviewer\Plugins\Tailviewer.Analysis.DataSources.0.7.tvp'
2019-09-26 13:46:46,493 [1] INFO  Tailviewer.Archiver.Plugins.PluginGroup - Loaded plugin 'C:\Program Files\Tailviewer\Plugins\Tailviewer.Analysis.Events.0.7.tvp'
2019-09-26 13:46:46,510 [1] INFO  Tailviewer.Archiver.Plugins.PluginGroup - Loaded plugin 'C:\Program Files\Tailviewer\Plugins\Tailviewer.Analysis.QuickInfo.0.7.tvp'
2019-09-26 13:46:46,514 [1] INFO  Tailviewer.Archiver.Plugins.PluginArchiveLoader - Loading plugins implementing 'IFileFormatPlugin'...
2019-09-26 13:46:46,515 [1] INFO  Tailviewer.Archiver.Plugins.PluginArchiveLoader - Loaded #0 plugins
2019-09-26 13:46:46,564 [1] ERROR Tailviewer.App - Caught unexpected exception: System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à Tailviewer.BusinessLogic.Bookmarks.BookmarkCollection.AddDataSource(IDataSource dataSource)
   à Tailviewer.BusinessLogic.DataSources.DataSources.AddDataSource(DataSource settings)
   à Tailviewer.BusinessLogic.DataSources.DataSources..ctor(ILogFileFactory logFileFactory, ITaskScheduler taskScheduler, IFilesystem filesystem, IDataSourcesSettings settings, IBookmarks bookmarks)
   à Tailviewer.App.StartApplication(IMutex mutex, String fileToOpen)
   à Tailviewer.App.StartInternal(IMutex mutex, String[] args)
   à Tailviewer.App.Start(IMutex mutex, String[] args)
`

Event Viewer  -> there is nothing  about Tailviewer (or about anything else).

Thanks.

**Comment by Kittyfisto** [comment]
No problem! That is indeed very useful. My french is a bit rusty but google translate could help me out ;)  
It looks like I made a mistake reading bookmarks from bookmarks.xml. You can try renaming %LocalAppData%\Tailviewer\bookmarks.xml and then try starting Tailviewer. That should solve it.

In the meantime, I'll see that this bug will be fixed with the next release.

**Comment by eNovware** [comment]
YES !  :o)
Tailviewer starts again, very big thanks !

**Comment by eNovware** [comment]
Should I close the issue ?

**Comment by Kittyfisto** [comment]
I'm glad it's working again.

You can leave it open as the bug is present in the current release: I'll close it once I've released a bugfix.

Thanks for reporting this issue!

**Comment by eNovware** [comment]
OK.
NB: where could I propose new feature for Tailviewer ?    :-)

**Comment by Kittyfisto** [comment]
You can simply open a new issue and state your request there. Depending on the scope it might be done quickly or take some time to complete though ;)

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
