### ISSUE TITLE
[New feature] 'cls' & 'display all again' buttons

### ISSUE THREAD

**Issue by eNovware** [Kittyfisto/Tailviewer#215]
a '**cls**' button should be a usefull tool : this button clear display and only display new lines from log files (but the log lines are not deleted from log files of course).

Usefull when debuging some code that output traces in log : new lines are clearly displayed.

A second '**display all again**' button could also be great to revert '**cls**' button effect ...

**Comment by Kittyfisto** [comment]
Thanks for the feedback. I like the feature and it shouldn't be too difficult to implement. I may be able to implement that this year (no promises though :P):

**Comment by Kittyfisto** [comment]
@eNovware It's taken some time, however your requested feature is finally available with the latest tailviewer build (v0.9.0.869) which you can download right now if you want to: https://ci.appveyor.com/project/Kittyfisto/sharptail/builds/30660183/artifacts. The feature will also be part of the next Tailviewer release.

**Comment by Kittyfisto** [comment]
Available with [v0.9.1](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.1)

**Comment by eNovware** [comment]
Great job, thanks !!!
