### ISSUE TITLE
[New feature] Fully customized color filter/higthlight

### ISSUE THREAD

**Issue by eNovware** [Kittyfisto/Tailviewer#216]
Allow user to fully cutomize the 6 entries '**Fatals/Errors/Warnings/Infos/Debug/Trace**' items :
  > Entry name
  > Search pattern (same has in filter, this one is perfect !!!)
  > Display color (back & front color)

**Comment by Kittyfisto** [comment]
That should be do-able. Currently, this can only be achieved by developing a [plugin](https://github.com/Kittyfisto/Tailviewer/tree/master/docs) however this should definitely be  configurable as a user.

I think you may not even be the first to request it - it shows that this could be useful for at least two people ;)

**Comment by Kittyfisto** [comment]
@eNovware This feature has finally been implemented and is available with [v0.9.3](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.3)!
