### ISSUE TITLE
Cannot uninstall release 0.8.1.701

### ISSUE THREAD

**Issue by PhilLab** [Kittyfisto/Tailviewer#219]
### Current behaviour

When trying to uninstall Tailviewer via Windows 10's "Add or remove programs", I just get an error dialog saying
> Windows cannot find 'TODO'. Make sure you typed the name correctly, and then try again.

![image](https://user-images.githubusercontent.com/1710255/66401717-e926e880-e9e3-11e9-9a04-0154e9f657a1.png)

### Expected behaviour
Uninstallation should be possible
### Steps to reproduce the problem
Install the release from Github, then try to deinstall

**Comment by Kittyfisto** [comment]
It's a shame you want to uinstall tailviewer, but thanks for reporting this issue ;)

I must have forgotten to implement this part. As a temporary workaround, you'll have to delete the "%ProgramFiles%\Tailviewer" folder manually. In case the entry of installed applications doesn't vanish, you can get rid of this in the following way:

[**Please make sure to backup the windows registry before doing those steps**](https://support.microsoft.com/en-us/help/322756/how-to-back-up-and-restore-the-registry-in-windows)

1. Open the registry editor by clicking start => regedit => enter
2. Navigate to *HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*
3. Find the folder named "Tailviewer"
4. Delete the entire folder

Once deleted, tailviewer should no longer be part of the list of installed applications on your system.

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.2](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.2)
