### ISSUE TITLE
Tailviewer may display the same log line multiple times in rare cases

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#221]
### Current behaviour

Under rare circumstances, see below, tailviewer will display certain lines of a log file multiple times in succession. This can appear in various patterns, for example (N, N, N+1, N+2, etc..) or (N, N+1, N, N+1, N+2, etc...).

### Expected behaviour

Tailviewer should not artificially duplicate lines and display them as they are in the origin log file.

### Steps to reproduce the problem

1. Create an empty log file
2. Open the log file in tailviewer
3. Open the log file in a text editor
4. Write some lines to the file in the text editor and hit save
5. **Continue** the last line written, then add at least two more lines, then hit save
6. Tailviewer will display the line which was continued in step 5 twice

### Workaround

Whenever this problem occurs, changing any filter of the log file will cause the problem to disappear. For example simply toggling (enabling/disabling or vice versa)  any non-empty filter will make this problem go away.

**Comment by Kittyfisto** [comment]
This problem currently only occurs when **all** of the following conditions are met:
- The log file being displayed is **currently** being written to
- The application writing to the log file writes a single line in multiple parts (i.e. write half of the line, flush, write second half of the line, flush)
- A race occurs where tailviewer is able to read the first half of the line **before** the application from above manages to write the second half

It is a very rare occurrence so far and has been reported by one colleague so far.  

The problem itself is caused by a bug in the `FilteredLogFile` class and should be able to be solved there.

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)

**Comment by AdrianEggenberger** [comment]
I have seen this behavior today in release 1.00 RC1. All the criteria from above seem to be given in my case. I have an application that writes log4net data to a text file. The Tailviewer is used to visualize the content with an active filter enabled.

In the duplicated lines even the line number is duplicated.
