### ISSUE TITLE
not able to copy log text

### ISSUE THREAD

**Issue by drjtan** [Kittyfisto/Tailviewer#230]
### Current behaviour

Trying to copy a log text, for example, a file path, a name, but doesn't seem to let me do that. Do me miss something obvious? It cannot be that I am the first one who need to copy text from a log.

### Expected behaviour

Being able to copy to clipboard.

### Steps to reproduce the problem

Just try to copy some text

**Comment by Kittyfisto** [comment]
You certainly aren't the first one. Currently you can only copy an entire line (or multiple ones) by selecting them and pressing ctrl+c.

There's neither a context menu, nor can you select passages of text, however I've gotten this request multiple times in the past so it may be time to implement it finally :)

Please let me know if the above doesn't help, then we may be dealing with a bug.

**Comment by drjtan** [comment]
thank you so much! Copying the entire line will do for now. It's a great tool.

**Comment by Kittyfisto** [comment]
You're welcome, I'm glad you like it and am thankful for all the feedback I get. Your report was the final straw that made me think I had to align Tailviewer's behaviour with other applications, so I might just implement #231 in the near future ;).
