### ISSUE TITLE
Add setting for tab size

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#232]
Today Tailviewer has a fixed non-configurable setting for tab size.

For the past ten+ years there're highly controversial discussions happening within the programming community whether it's better to use tabs or spaces and if spaces how much space should form a tab.
Without picking the fight and choose one side over the other it would be nice to have a Tailviewer setting to specify the tab size in units of spaces.

**Comment by Kittyfisto** [comment]
@BenKenobi85 This has been implemented with Tailviewer [v0.9.2.881](https://ci.appveyor.com/project/Kittyfisto/sharptail/builds/32077267/artifacts). If you've got the time, please give it a try. It will most certainly be part of the next official release, however I think I might have to fix #235 first.

**Comment by Kittyfisto** [comment]
Available with [v0.9.3](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.3)
