### ISSUE TITLE
Tabs in logfile messes up search highlighting

### ISSUE THREAD

**Issue by zigurana** [Kittyfisto/Tailviewer#244]
### Current behaviour

When searching in a file, the found entries cause highlighting of the text, but at an offset of the matches, see screenshot.
![image](https://user-images.githubusercontent.com/6103768/101336622-facf7e80-387a-11eb-8fad-a8c9e8e2ab6e.png)

This effect depends on the amount of tabs found in the line.
### Expected behaviour
Highlights overlaps with found match, independent of tabs being present or not.

### Steps to reproduce the problem
Open minimal example file (attached), search for 'tab', observe highlighting
[minimal_example.txt](https://github.com/Kittyfisto/Tailviewer/files/5651891/minimal_example.txt)

PS: likely related to: https://github.com/Kittyfisto/Tailviewer/issues/44, but a different symptom

**Comment by Kittyfisto** [comment]
@zigurana Thank you for reporting and analysing this issue. I've found the mistake and should have a bugfix ready soon.

**Comment by Kittyfisto** [comment]
@zigurana This bug has been fixed with Tailviewer [v0.9.3.892](https://ci.appveyor.com/project/Kittyfisto/sharptail/builds/36750308/artifacts) and will be part of the next Tailviewer release.
