### ISSUE TITLE
Search function does not reset hit counter when files have been re-created

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#288]
While working with a merged data source consiting of several logfiles, I've encountered a situation where the counter inside the search text box does not reset to zero in case the correspoding file has been re-created on the disk.

![image](https://user-images.githubusercontent.com/26541111/108473286-206f0000-728e-11eb-8168-fd616cc26fd3.png)

Let's assume the merged data source consists of several files, and as shown in picture, we for example search for every occurence of the term 'seconds' which in this case has 105 hits. Restarting the application under test re-creates all log file being part of the merged data source, by deleting and re-creating the files. As the files are empty upon start we expect the search box the reset the hit count to zero, which was not the case in my test.

**Comment by Kittyfisto** [comment]
Fixed with [Tailviewer v1.0.0-RC1](https://github.com/Kittyfisto/Tailviewer/releases/tag/v1.0.0-rc1).
