### ISSUE TITLE
Add command to go to next / previous data source

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#299]
At the moment the user can go to a data source, but this is a hidden feature and only the most adventurous users stumble upon it by accident:

- [x] Add "Go to next data source" command to the "Edit" menu which may only be executed when at least one data source is opened
- [x] Add "Go to previous data source" command to the "Edit" menu which may only be executed when at least one data source is opened
- [x] Make sure the shortcuts to invoke the command are displayed (Ctrl+Tab, Ctrl+Shift+Tab)

**Comment by kb9gxk** [comment]
> At the moment the user can go to a data source, but this is a hidden feature and only the most adventurous users stumble upon it by accident:
> 
> * [x]  Add "Go to next data source" command to the "Edit" menu which may only be executed when at least one data source is opened
> * [x]  Add "Go to previous data source" command to the "Edit" menu which may only be executed when at least one data source is opened
> * [x]  Make sure the shortcuts to invoke the command are displayed (Ctrl+Tab, Ctrl+Shift+Tab)

The Ctrl+Tab and Ctrl+Shift+Tab does not work.
