### ISSUE TITLE
"Open in explorer" button is not working when the file doesn't exist on disk

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Tailviewer#60]
The "open in explorer" button usually opens the windows explorer in the file's folder *and* selects the file.
If the file doesn't exist, the explorer is opened at a completely different folder. This should be changed so that if the file doesn't exist, then the deepest folder that exists should be opened:

If the file path is C:\foo\bar\fizz.txt:
- If fizz.txt exists, then C:\foo\bar should be opened and fizz.txt should be selected
- If fizz.txt doesn't exist, then C:\foo\bar should be opened
- If bar doesn't exist, then C:\foo should be opened
- etc...

**Comment by Kittyfisto** [comment]
The code that checks for the existance of a file may NOT run on the UI thread (as File.Exists blocks for a considerable amount of time, if unlucky), therefore the entire action must be postponed to a background thread and the user should be notified that something is being performed while the existance is being checked...

**Comment by oleg-abr** [comment]
I'll take this one.

**Comment by Kittyfisto** [comment]
Sure thing, try to use [FileEx.Exists](https://github.com/Kittyfisto/Tailviewer/commit/53d655b0a58975a244a6953c439e6610b1b81029#diff-c4b5cdc0d447a62ff63d8d6b1045ae44) asynchronously.
