### ISSUE TITLE
copy and paste

### ISSUE THREAD

**Issue by jlanzarotta** [Kittyfisto/Tailviewer#68]
Hello,

How does one copy lines from the view into some other application?  I cannot seem to be able to copy lines...

Thanks.

**Comment by Kittyfisto** [comment]
Hi,

that's strange. I just tried it with the latest version: Select a line (or multiple lines) and then press control+c copy that line. Pasting it into notepad++ worked fine for me.

What operating system are you using and into which application are you trying to copy a line to?

**Comment by jlanzarotta** [comment]
Windows 7 x64... pasting into Notepad...

**Comment by jlanzarotta** [comment]
I assume you select multiple lines using SHIFT and Down Arrow?

**Comment by Kittyfisto** [comment]
Currently, you can select a region of lines by holding shift and clicking them with the mouse. Shift and down/up arrow doesn't work, unfortunately: I've added a separate issue for this #69 (It should be an easy fix and be ready within the next few days).

Back to the original issue: Would you mind sending me the log file located under "%localappdata%\Tailviewer\Tailviewer.log"? It might contain some information on why this won't work on your computer.

**Comment by jlanzarotta** [comment]
Okay, sorry... user error.  I thought that Shift and down/up arrow worked.  I did not realize I needed to Shift and Mouse click the lines.  It is working as designed...

**Comment by Kittyfisto** [comment]
No problem. Guess I'll have to improve the design thanks to you :p

**Comment by jlanzarotta** [comment]
:)
Thanks for a great application.  I use it all the time.

**Comment by Kittyfisto** [comment]
Thanks for the praise: I'm glad you like it.
Feel free to post any suggestion or feature you're missing: I'll happily add them.

**Comment by jlanzarotta** [comment]
Fantastic!  Will do.
